# traefik_dynamic.yml

http:
  middlewares:
    secure-api:
      plugin:
        jwt:
          issuers:
            - http://localhost/keycloak/realms/dachub
#          Alternatively can try static public key
#          secret: |
#            -----BEGIN RSA PUBLIC KEY-----
#            {static RSA public key}
#            -----END RSA PUBLIC KEY-----
